USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_USP_PRODUCTCONTRIBUTIONREPORT]    Script Date: 9/16/2019 7:25:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ACX_USP_PRODUCTCONTRIBUTIONREPORT]              
(@SITEID nvarchar(max)='',            
@STARTDATE smalldatetime ,            
@ENDDATE smalldatetime,             
@Category nvarchar(30)='',            
@SubCategory nvarchar(50)='',             
@Product nvarchar(10)='',             
@CustGroup nvarchar(10)='',            
@StateCode nvarchar(10)='',            
@UserCode nvarchar(50)='',            
@UserType nvarchar(50)='',
@BUCODE NVARCHAR(10)='')  AS            
BEGIN  

IF OBJECT_ID('TEMPDB..#TMPSTATE') IS NOT NULL BEGIN DROP TABLE #TMPSTATE END     
CREATE TABLE #TMPSTATE (STATEID NVARCHAR(50));    

IF LEN(@StateCode)>0    
BEGIN   INSERT INTO #TMPSTATE SELECT ID FROM DBO.CommaDelimitedToTable(@StateCode,',') END    
ELSE    
BEGIN INSERT INTO #TMPSTATE SELECT DISTINCT STATEID FROM AX.LOGISTICSADDRESSSTATE WHERE LEN(STATEID)>0 END     
 
IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END    
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(50));              
IF LEN(@SITEID)>0               
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',')   END    
ELSE IF (@UserType != 3)    
BEGIN INSERT INTO #TMPSITELIST select SITEID from AX.InventSite WHERE LEN(SITEID)>0  AND STATECODE IN (SELECT STATEID FROM #TMPSTATE) END     
ELSE     
BEGIN INSERT INTO #TMPSITELIST SELECT Distinct DISTRIBUTOR  FROM DBO.UDF_GetSALESHIERARCHY(@UserCode) WHERE [STATE] IN (SELECT STATEID FROM #TMPSTATE)  END    

IF OBJECT_ID('TEMPDB..#TMPCHNGROUP') IS NOT NULL BEGIN DROP TABLE #TMPCHNGROUP END                  
CREATE TABLE #TMPCHNGROUP (CHANNELGROUPCODE NVARCHAR(50));                
IF (@UserType != 3)                
BEGIN   INSERT INTO #TMPCHNGROUP SELECT DISTINCT CUST_GROUP FROM AX.ACXCUSTMASTER  END              
ELSE              
BEGIN  INSERT INTO #TMPCHNGROUP SELECT CHANNELGROUPCODE FROM DBO.UDF_GETCHANNELGROUPBYUSER(@UserCode)  END              

--IF OBJECT_ID('TEMPDB..#TMPPRDGROUP') IS NOT NULL BEGIN DROP TABLE #TMPPRDGROUP END                  
--CREATE TABLE #TMPPRDGROUP (PRODUCTGROUP NVARCHAR(50));                
--IF (LEN(@Category)=0)                
--BEGIN   INSERT INTO #TMPPRDGROUP SELECT DISTINCT PRODUCT_GROUP FROM AX.INVENTTABLE  END              
--ELSE              
--BEGIN  INSERT INTO #TMPPRDGROUP SELECT @Category  END              

--IF OBJECT_ID('TEMPDB..#TMPPRDSUBGROUP') IS NOT NULL BEGIN DROP TABLE #TMPPRDSUBGROUP END                  
--CREATE TABLE #TMPPRDSUBGROUP (PRODUCTSUBGROUP NVARCHAR(50));                
--IF (LEN(@SubCategory )=0)                
--BEGIN   INSERT INTO #TMPPRDSUBGROUP SELECT DISTINCT PRODUCT_SUBCATEGORY FROM AX.INVENTTABLE  END              
--ELSE              
--BEGIN  INSERT INTO #TMPPRDSUBGROUP SELECT @SubCategory   END              

--IF OBJECT_ID('TEMPDB..#TMPPRD') IS NOT NULL BEGIN DROP TABLE #TMPPRD END                  
--CREATE TABLE #TMPPRD (PRODUCTCODE NVARCHAR(50));                
--IF (LEN(@Product)=0)                
--BEGIN   INSERT INTO #TMPPRD SELECT DISTINCT ITEMID FROM AX.INVENTTABLE  END              
--ELSE              
--BEGIN  INSERT INTO #TMPPRD SELECT @Product END              

-------BUCODE-------  
IF OBJECT_ID('tempdb..#tmpBuCode') IS NOT NULL BEGIN DROP TABLE #tmpBuCode  END   
CREATE TABLE #tmpBuCode (BU_CODE NVARCHAR(10))  
IF LEN(@BUCODE)>0  
BEGIN INSERT INTO #tmpBuCode SELECT ID FROM DBO.CommaDelimitedToTable(@BUCODE,',') 
END  
ELSE
BEGIN INSERT INTO #tmpBuCode SELECT distinct BU_CODE FROM AX.ACXSITEBUMAPPING WHERE SITEID IN (SELECT SITEID FROM #TMPSITELIST)
END

--SELECT * FROM #TMPPRDGROUP
--SELECT CHANNELGROUPCODE FROM #TMPCHNGROUP      
  
SELECT BU_CODE [BU CODE],BU_DESC [BU NAME],PRODUCT_GROUP,PRODUCT_SUBCATEGORY,PRODUCT_CODE,PRODUCT_NAME,        
ISNULL(SUM(CASE WHEN ([INVOICE DATE]>=@STARTDATE AND [INVOICE DATE]<=@ENDDATE) THEN LTR ELSE 0 END),0) LTR,        
ISNULL(SUM(CASE WHEN ([INVOICE DATE]>=DATEADD(yy,-1,@STARTDATE) AND [INVOICE DATE]<=DATEADD(yy,-1,@ENDDATE)) THEN LTR ELSE 0 END),0) LAST_YR_LTR          
FROM VW_SALEREGISTER SR
--JOIN #TMPPRDGROUP PG ON PG.[PRODUCTGROUP]=SR.[PRODUCT_GROUP]
--JOIN #TMPPRDSUBGROUP SG ON SG.[PRODUCTSUBGROUP]=SR.[PRODUCT_SUBCATEGORY]
--JOIN #TMPPRD P ON P.PRODUCTCODE=SR.[PRODUCT_CODE]
JOIN #TMPSITELIST SL ON SR.[DIST. CODE]=SL.SITEID
JOIN #TMPCHNGROUP CGP ON CGP.CHANNELGROUPCODE=SR.CUST_GROUP_CODE
--
WHERE (([INVOICE DATE]>=@STARTDATE AND [INVOICE DATE]<=@ENDDATE)   OR        
([INVOICE DATE]>=DATEADD(yy,-1,@STARTDATE) AND [INVOICE DATE]<=DATEADD(yy,-1,@ENDDATE)))        
--AND PRODUCT_GROUP LIKE CASE WHEN LEN(@Category)>0 THEN @Category ELSE'%' END          
--AND PRODUCT_SUBCATEGORY LIKE CASE WHEN LEN(@SubCategory )>0 THEN @SubCategory ELSE '%' END          
--AND PRODUCT_CODE LIKE CASE WHEN LEN(@Product )>0 THEN  @Product ELSE '%' END           
AND CUST_GROUP_CODE LIKE CASE WHEN LEN(@CustGroup )>0 THEN  @CustGroup ELSE '%' END           
AND BU_CODE IN (SELECT BU_CODE FROM #tmpBuCode)
--AND CUST_GROUP_CODE IN (SELECT CHANNELGROUPCODE FROM #TMPCHNGROUP)     
AND (Isnull(@Category,'')='' or @Category=[PRODUCT_GROUP]) 
AND (Isnull(@SubCategory,'')='' or @SubCategory=[PRODUCT_SUBCATEGORY]) 
AND (Isnull(@Product,'')='' or @Product=[PRODUCT_CODE]) 
GROUP BY BU_CODE,BU_DESC,PRODUCT_GROUP,PRODUCT_SUBCATEGORY,PRODUCT_CODE,PRODUCT_NAME        
ORDER BY PRODUCT_GROUP,PRODUCT_SUBCATEGORY,PRODUCT_NAME,PRODUCT_CODE        
END