USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_USP_PSRDSR_HEADER]    Script Date: 10/31/2019 6:16:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--EXEC ACX_USP_PSRDSR_HEADER '000059144','PSRACXIOM','2016-09-01'
ALTER PROCEDURE [dbo].[ACX_USP_PSRDSR_HEADER] (@SITECODE NVARCHAR(Max),@PSRCODE NVARCHAR(20),@DATE SMALLDATETIME)
AS
BEGIN
	
	IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
	CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
	IF LEN(@SITECODE)>0                     
	BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITECODE,',')   END     

	DECLARE @TOWN NVARCHAR(100),@AREA NVARCHAR(100),@PSRNAME NVARCHAR(100),@ROUTE NVARCHAR(MAX),@TARGET DECIMAL(18,2)
	DECLARE @FROMDATE SMALLDATETIME,@TODATE SMALLDATETIME
	DECLARE @ROUTE1 NVARCHAR(100),@ROUTE2 NVARCHAR(100),@ROUTE3 NVARCHAR(MAX)
	--SELECT @SITECODE='000059144',@PSRCODE='PSRACXIOM',@DATE='2016-07-01'
	SELECT @FROMDATE=CONVERT(NVARCHAR,YEAR(@DATE)) + '-' + CONVERT(NVARCHAR,MONTH(@DATE)) +'-01'
	SELECT @TODATE=CONVERT(NVARCHAR,YEAR(@DATE)) + '-' + CONVERT(NVARCHAR,MONTH(@DATE)) +'-' +CONVERT(NVARCHAR,DAY(EOMONTH(@Date)))
	SELECT @PSRNAME=PSR_NAME + '(' + CONTACTNO +')' FROM AX.ACXPSRMaster WHERE PSR_CODE=@PSRCODE
	SELECT @TOWN=ACXCITY,@AREA=ACXCITY FROM AX.INVENTSITE WHERE SITEID IN (SELECT SITEID FROM #TMPSITELIST)
	SELECT   @ROUTE= COALESCE(@ROUTE+ ', ','') +  BEATNAME FROM
	(SELECT DISTINCT BEATNAME FROM AX.ACXPSRBeatMaster BM WHERE PSRCODE=@PSRCODE AND SITE_CODE IN (SELECT SITEID FROM #TMPSITELIST))
	AS A  
	SELECT @TARGET=ISNULL(MAX([TARGET]),0) FROM AX.ACXTARGETLINE WHERE SITEID IN (SELECT SITEID FROM #TMPSITELIST) AND OBJECTCODE=@PSRCODE
	AND STARTDATE>=@FROMDATE AND ENDDATE<=@TODATE
SELECT TOP 1 @ROUTE1=ID FROM [dbo].[CommaDelimitedToTable](@ROUTE,',')
SELECT TOP 1 @ROUTE2=ID FROM [dbo].[CommaDelimitedToTable](@ROUTE,',') WHERE ID NOT IN (@ROUTE1)
SELECT @ROUTE3=COALESCE(@ROUTE3+ ', ','') +  ID FROM [dbo].[CommaDelimitedToTable](@ROUTE,',') WHERE ID NOT IN (@ROUTE1,@ROUTE2)
SELECT @DATE [DATE],DAY(EOMONTH(@Date)) AS DaysInMonth,@PSRNAME PSRNAME,@TOWN TOWN,@AREA AREA,ISNULL(@ROUTE1,'') R0UTE1,ISNULL(@ROUTE2,'') R0UTE2,ISNULL(@ROUTE3,'') R0UTE3,@TARGET [TARGET]
END
