USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_USP_VRSTransactionDetails]    Script Date: 10/29/2019 5:07:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[ACX_USP_VRSTransactionDetails]
(

@StateCode nvarchar(max)= '',
@Site_Code nvarchar(max)= '',
@VRSCode nvarchar(20)= '',
@DATAAREAID nvarchar(4)= '',
@StartDate Date = '',
@EndDate Date='',
@subcategory nvarchar(30) = ''
)

As

BEGIN

SET NOCOUNT ON;

IF OBJECT_ID('TEMPDB..#TMPSTATELIST') IS NOT NULL BEGIN DROP TABLE #TMPSTATELIST END          
CREATE TABLE #TMPSTATELIST (SATECODE NVARCHAR(20));                    
IF LEN(@StateCode)>0                     
BEGIN INSERT INTO #TMPSTATELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@StateCode,',')   END    

IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
IF LEN(@Site_Code)>0                     
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@Site_Code,',')   END     
 

SELECT A.VRS_CODE,D.CUSTOMER_NAME AS VRSNAME,A.CUSTOMER_CODE AS VDCODE,D1.CUSTOMER_NAME AS VDNAME,B.PRODUCT_CODE AS ITEMCODE
, A.VRSISSUE_NO,CONVERT(VARCHAR(11),A.VRSISSUE_DATE,106) DATE,

CASE WHEN A.OrderType=1 THEN 'ISSUE' WHEN A.OrderType=2 THEN 'RETURN' END AS ORDERTYPE, 

C.PRODUCT_GROUP,C.PRODUCT_NAME,C.PRODUCT_NICKNAME,

--CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END  * case when B.UOM='PCS' then ROUND(B.BOX/ISNULL(C.Product_PackSize,1),2) else B.BOX end as Box

CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END  *  B.BoxQty as BoxQty
,CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END  *  B.PcsQty as PcsQty
,CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END  *  CAST(B.BOX AS DECIMAL(9,2)) as QtyConv
--,CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END * isnull(B.BoxPcs,0) as BoxPcs
,CASE WHEN A.OrderType=2 THEN -CAST(isnull(B.BoxPcs,0) AS DECIMAL (9,2)) ELSE isnull(B.BoxPcs,0) END   as BoxPcs

,(CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END * 
CASE WHEN B.UOM='Box' THEN ROUND((B.BOX * C.LTR * ISNULL(C.Product_PackSize,1))/1000,2) else ROUND((B.BOX * C.LTR)/1000,2) end) as Ltr
,CONVERT(DECIMAL(18,2),RATE) RATE,TAXVALUE [TAX],(CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END ) * TAXAMOUNT [TAX AMOUNT],
ADDTAXVALUE [ADD TAX],(CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END ) * ADDTAXAMOUNT [ADD TAX AMT],
CONVERT(DECIMAL(18,2),(CASE WHEN A.OrderType=2 THEN -1 ELSE 1 END ) * AMOUNT) [AMOUNT]
FROM AX.ACXVRSISSUEHEADER A 

INNER JOIN AX.ACXVRSISSUELINE B ON A.CUSTOMER_CODE = B.CUSTOMER_CODE AND A.SITEID = B.SITEID AND A.VRSISSUE_NO = B.VRSISSUE_NO

LEFT OUTER JOIN AX.INVENTTABLE C ON B.PRODUCT_CODE = C.ITEMID 

LEFT OUTER JOIN AX.ACXCUSTMASTER D ON A.VRS_CODE = D.CUSTOMER_CODE AND A.SITEID = D.SITE_CODE

LEFT OUTER JOIN AX.ACXCUSTMASTER D1 ON A.CUSTOMER_CODE = D1.CUSTOMER_CODE AND A.SITEID = D1.SITE_CODE

Where 
--A.SITEID like case when @Site_Code='' then '%' else @Site_Code end
(A.SITEID IN (SELECT SITEID FROM #TMPSITELIST) OR isnull(@Site_Code,'')='')
and (D.STATE IN (SELECT SATECODE FROM #TMPSTATELIST) OR isnull(@StateCode,'')='')
--and D.State like case when @StateCode='' then '%' else @StateCode end
and A.VRS_CODE like case when @VRSCode='' then '%' else @VRSCode end
and A.DATAAREAID=@DATAAREAID 
and CONVERT(SMALLDATETIME,CONVERT(NVARCHAR,A.VRSISSUE_DATE,106))>=@StartDate 
and CONVERT(SMALLDATETIME,CONVERT(NVARCHAR,A.VRSISSUE_DATE,106))<=@EndDate
and c.Product_Subcategory like case when  @subcategory = '' then '%' else @subcategory end

order by A.VRS_CODE,D.CUSTOMER_NAME,A.VRSISSUE_DATE,A.VRSISSUE_NO
end
