USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_USP_PSRDSR]    Script Date: 10/31/2019 6:10:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--EXEC ACX_USP_PSRDSR '0000600079','P01054','2/1/2018 12:00:00 AM'

ALTER PROCEDURE [dbo].[ACX_USP_PSRDSR] (@SITECODE NVARCHAR(max),@PSRCODE NVARCHAR(20),@DATE SMALLDATETIME)

AS

BEGIN

--SELECT @SITECODE='0000601426',@PSRCODE='P00001',@DATE='2016-09-01'

IF OBJECT_ID('TEMPDB..#TMPBEAT') IS NOT NULL BEGIN DROP TABLE #TMPBEAT END

IF OBJECT_ID('TEMPDB..#TMPDATE') IS NOT NULL BEGIN DROP TABLE #TMPDATE END

IF OBJECT_ID('TEMPDB..#TMPFINALRST') IS NOT NULL BEGIN DROP TABLE #TMPFINALRST END



CREATE TABLE #TMPDATE (DATE SMALLDATETIME,DAYOFDATE NVARCHAR(20))

DECLARE @DAY INT,@DATECHECK SMALLDATETIME

SET @DAY=1

WHILE @DAY<=DAY(EOMONTH(@Date)) 

BEGIN

	SET @DATECHECK=CONVERT(NVARCHAR,YEAR(@Date)) + '-' + CONVERT(NVARCHAR,MONTH(@Date)) + '-' + CONVERT(NVARCHAR,@DAY)

	INSERT INTO #TMPDATE SELECT @DATECHECK,datename(dw,@DATECHECK)

	SET @DAY+=1

END

 
IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
IF LEN(@SITECODE)>0                     
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITECODE,',')   END    

--DATE WISE ROUTE NO

SELECT DISTINCT R1.[DATE],(SELECT TOP 1 BEATNAME FROM AX.ACXPSRBeatMaster 

	WHERE BEATCODE=(SELECT TOP 1 PSR_BEAT FROM AX.ACXCUSTMASTER WHERE CUSTOMER_CODE=R1.CUSTOMERCODE AND SITE_CODE IN (SELECT SITEID FROM #TMPSITELIST)

	 ) AND SITE_CODE IN (SELECT SITEID FROM #TMPSITELIST) AND PSRCODE=@PSRCODE) BEATNAME

	INTO #TMPBEAT FROM (SELECT CONVERT(DATE,STATUSDATE) [DATE],CUSTOMERCODE 

		FROM AX.ACXSHOPSTATUSENTRY 

		WHERE PSRCODE=@PSRCODE AND SITECODE IN (SELECT SITEID FROM #TMPSITELIST) AND MONTH(STATUSDATE)=MONTH(@DATE) 

		AND YEAR(STATUSDATE)=YEAR(@DATE)

		GROUP BY CONVERT(DATE,STATUSDATE),CUSTOMERCODE

	) AS R1

;WITH CTE1 AS--DATE WISE TOTAL CALLS

(SELECT DISTINCT R1.[DATE],COUNT(*) [TOTALCALLS] FROM (SELECT CONVERT(DATE,STATUSDATE) [DATE],CUSTOMERCODE 

		FROM AX.ACXSHOPSTATUSENTRY 

		WHERE PSRCODE=@PSRCODE AND SITECODE IN (SELECT SITEID FROM #TMPSITELIST) AND MONTH(STATUSDATE)=MONTH(@DATE) 

		AND YEAR(STATUSDATE)=YEAR(@DATE)

		GROUP BY CONVERT(DATE,STATUSDATE),CUSTOMERCODE

	) AS R1 GROUP BY R1.[DATE]

),CTE2 AS --DATE WISE ROUTE 

(SELECT DISTINCT	T1.[DATE],

 		STUFF((SELECT DISTINCT TOP 100 PERCENT ',' + T2.[BEATNAME] 

		FROM #TMPBEAT AS T2 WHERE T2.[DATE] = T1.[DATE]

		ORDER BY ',' + T2.[BEATNAME] FOR XML PATH('')), 1, 1, '') AS ROUTENO

		FROM #TMPBEAT AS T1 

),CTE3 AS --TOTAL PRODUCTIVE CALLS

(SELECT R1.[DATE],COUNT(*) [PRODUCTIVE_CALLS],SUM(ORDAMT) ORDAMOUNT 

		FROM (SELECT CONVERT(DATE,SO_APPROVEDATE) [DATE],CUSTOMER_CODE,SUM(SO_VALUE) ORDAMT 

				FROM VW_SALESHEADER WHERE PSR_CODE=@PSRCODE AND SITEID IN (SELECT SITEID FROM #TMPSITELIST) 

				AND MONTH(SO_APPROVEDATE)=MONTH(@DATE) 

				AND YEAR(SO_APPROVEDATE)=YEAR(@DATE)

				GROUP BY CONVERT(DATE,SO_APPROVEDATE),CUSTOMER_CODE

			) AS R1 GROUP BY R1.[DATE]

),CTE4 AS --TOTAL BILLING AMOUNT

(

SELECT R2.[DATE],SUM(R2.BILLING_AMOUNT) BILLING_AMOUNT FROM 

	(SELECT INVOIC_DATE [DATE],SUM(INVOICE_VALUE) BILLING_AMOUNT FROM AX.ACXSALEINVOICEHEADER SH

	JOIN VW_SALESHEADER SO ON SO.INVOICE_NO=SH.INVOICE_NO AND SO.SITEID=SH.SITEID

	WHERE SO.PSR_CODE=@PSRCODE --SH.CUSTOMER_CODE IN (SELECT CUSTOMER_CODE FROM AX.ACXCUSTMASTER WHERE PSR_CODE=@PSRCODE) 

		AND SH.SITEID IN (SELECT SITEID FROM #TMPSITELIST) AND TRANTYPE=1

		AND MONTH(SH.INVOIC_DATE)=MONTH(@DATE) 

		AND YEAR(SH.INVOIC_DATE)=YEAR(@DATE)

	GROUP BY INVOIC_DATE

	UNION 

	SELECT INVOIC_DATE [DATE],SUM(-INVOICE_VALUE) BILLING_AMOUNT FROM AX.ACXSALEINVOICEHEADER SH

	JOIN VW_SALESHEADER SO ON SO.INVOICE_NO=SH.SO_NO AND SO.SITEID=SH.SITEID

	WHERE SO.PSR_CODE=@PSRCODE --SH.CUSTOMER_CODE IN (SELECT CUSTOMER_CODE FROM AX.ACXCUSTMASTER WHERE PSR_CODE=@PSRCODE) 

		AND SH.SITEID IN (SELECT SITEID FROM #TMPSITELIST) AND TRANTYPE=2

		AND MONTH(SH.INVOIC_DATE)=MONTH(@DATE) 

		AND YEAR(SH.INVOIC_DATE)=YEAR(@DATE)

	GROUP BY INVOIC_DATE) AS R2 GROUP BY R2.DATE

)

SELECT Convert(nvarchar,T1.[DATE],106) [DATE],T1.DAYOFDATE [DAY],ISNULL(CTE2.[ROUTENO],'') [ROUTENO],

	ISNULL(CTE1.[TOTALCALLS],0) [TOTALCALLS],ISNULL(CTE3.[PRODUCTIVE_CALLS],0) [PRODUCTIVE_CALLS],

	CONVERT(DECIMAL(18,2),ISNULL(CTE3.[ORDAMOUNT],0)) [ORDAMOUNT],

	CONVERT(DECIMAL(18,2),ISNULL(CTE4.[BILLING_AMOUNT],0)) [BILLING_AMOUNT] 

INTO #TMPFINALRST FROM #TMPDATE T1

LEFT OUTER JOIN CTE1 ON CTE1.[DATE]=T1.[DATE]

LEFT OUTER JOIN CTE2 ON CTE2.[DATE]=T1.[DATE]

LEFT OUTER JOIN CTE3 ON CTE3.[DATE]=T1.[DATE]

LEFT OUTER JOIN CTE4 ON CTE4.[DATE]=T1.[DATE]



SELECT * FROM #TMPFINALRST WHERE TOTALCALLS>0 OR PRODUCTIVE_CALLS>0 OR ORDAMOUNT>0 OR BILLING_AMOUNT>0

END
