USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_DESTRUCTIONREPORT]    Script Date: 10/29/2019 7:12:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[ACX_DESTRUCTIONREPORT]

(@SITEID NVARCHAR(max),@STATECODE NVARCHAR(20),@FROMDATE SMALLDATETIME,@TODATE SMALLDATETIME,@ReportType nVarchar(10),@BUCODE NVARCHAR(10)='')

AS 

BEGIN

----------DESTRUCTION Type-------------------

IF OBJECT_ID('tempdb..#tmpReportType') IS NOT NULL BEGIN DROP TABLE #tmpReportType END 

CREATE TABLE #tmpReportType (ReportType nVarchar(10))

IF LEN(@ReportType)>0

BEGIN	INSERT INTO #tmpReportType SELECT ID FROM DBO.CommaDelimitedToTable(@ReportType,',')	END

ELSE

BEGIN INSERT INTO #tmpReportType select distinct cast(distructiontype as nVarchar(10)) distructiontype from [ax].[ACXDISTRUCTIONNOTE]

END

-----------------------------

IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
IF LEN(@SITEID)>0                     
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',')   END  


-------BUCODE-------  

 IF OBJECT_ID('tempdb..#tmpBuCode') IS NOT NULL BEGIN DROP TABLE #tmpBuCode  END   

 CREATE TABLE #tmpBuCode (BU_CODE NVARCHAR(10))  

 IF LEN(@BUCODE)>0  

 BEGIN INSERT INTO #tmpBuCode SELECT ID FROM DBO.CommaDelimitedToTable(@BUCODE,',') 

 END  

 ELSE

 
 BEGIN INSERT INTO #tmpBuCode SELECT BU_CODE FROM AX.ACXSITEBUMAPPING WHERE SITEID  IN (SELECT SITEID FROM #TMPSITELIST)

 END



SELECT ROW_NUMBER() OVER(ORDER BY (SELECT 1)) SNO,isnull(DT.Customer_code,'')+'-'+isnull(CT.Customer_Name,'') Customer,IT.BU_CODE [BU CODE], BU.BU_DESC [BU NAME],

PRODUCTCODE + '-' + PRODUCT_NAME AS PRODUCTS, BOX AS UNITS,

 (BOX * (CASE WHEN IT.PRODUCT_CRATE_PACKSIZE=0 THEN 1 ELSE IT.PRODUCT_CRATE_PACKSIZE END)) - (CONVERT(BIGINT,BOX) * (CASE WHEN IT.PRODUCT_CRATE_PACKSIZE=0 THEN 1 ELSE IT.PRODUCT_CRATE_PACKSIZE END)) PCS,



--MOD(BOX,(CASE WHEN IT.PRODUCT_CRATE_PACKSIZE=0 THEN 1 ELSE IT.PRODUCT_CRATE_PACKSIZE END))  PCS,

'' DAMAGE,CASE DISTRUCTIONTYPE WHEN 0 THEN 'PRIMARY-MELTAGE DESTRUCTION' 

WHEN 1 THEN 'COLDROOM DESTRUCTION' WHEN 2 THEN 'MARKET DESTRUCTION' END AS DISTRUCTIONTYPE,Invoice_No,CONVERT(NVARCHAR,InvoiceDate,106) as InvoiceDate,

CONVERT(NVARCHAR,MDF,106) MFD,BATCHNO,PRICE, REMARK AS REASON,VALUE TOTALVALUE

from [ax].[ACXDISTRUCTIONNOTE] AS DT

JOIN AX.INVENTTABLE IT ON DT.PRODUCTCODE=IT.ITEMID

JOIN [AX].[ACXBUMASTER] BU ON BU.BU_CODE = IT.BU_CODE

left outer join ax.acxcustmaster CT on Ct.Customer_code=DT.Customer_Code

WHERE 

CONVERT(SMALLDATETIME,CONVERT(NVARCHAR,DT.CREATEDDATETIME,106))>=@FROMDATE AND 

CONVERT(SMALLDATETIME,CONVERT(NVARCHAR,DT.CREATEDDATETIME,106))<=@TODATE 

and dt.SITEID IN (SELECT SITEID FROM #TMPSITELIST) 
and dt.distructiontype  IN (SELECT ReportType FROM #tmpReportType)

AND IT.BU_CODE IN (SELECT BU_CODE FROM #tmpBuCode)

END