USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_USP_PurchaseRegister]    Script Date: 10/9/2019 8:02:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
  
--exec [dbo].[ACX_USP_PurchaseRegister] '10006526','7200','01-Jan-2018','09-Oct-2019'    
ALTER Procedure [dbo].[ACX_USP_PurchaseRegister]    
(    
@Site_Code nvarchar(Max)=0,     
@DATAAREAID nvarchar(4)=0,@StartDate Date = '',@EndDate Date='')    
As    
BEGIN    
SET NOCOUNT ON;    

IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
IF LEN(@Site_Code)>0                     
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@Site_Code,',')   END     


SELECT * FROM VW_PURCHASEREGISTER WHERE CUSTOMER_CODE IN (SELECT SITEID FROM #TMPSITELIST)   
 AND [SALE_INVOICEDATE]>= @StartDate and [SALE_INVOICEDATE]<=@EndDate   
order by [RECEIPT DATE],[RECEIPT NO],PRODUCT    
  
--SELECT  
-- PIH.SITE_CODE CUSTOMER_CODE,IV.NAME [CUSTOMER NAME],PIL.PURCH_RECIEPTNO,PIH.DOCUMENT_NO, CONVERT(nvarchar(20), PIH.DOCUMENT_DATE,105) RECEIPTDATE,  
-- GSTINVOICENO,DISTGSTINNO,  
-- CASE WHEN ISNULL(DISTGSTINREGDATE,'1900-01-01')='1900-01-01' THEN '' ELSE CONVERT(NVARCHAR,DISTGSTINREGDATE,106) END DISTGSTINREGDATE,DISTCOMPOSITIONSCHEME,  
-- PIH.SALE_INVOICENO,CONVERT(nvarchar(20), PIH.SALE_INVOICEDATE,105) as SALE_INVOICEDATE ,  
-- PIH.PURCH_INDENTNO,PIH.PURCH_INDENTDATE,OrderTypeCode [ORDER TYPE],INVT.PRODUCT_GROUP,   
-- PIL.PRODUCT_CODE,(PIL.PRODUCT_CODE +'-'+ INVT.PRODUCT_NAME) PRODUCT,    
-- INVT.PRODUCT_SUBCATEGORY,INVT.HSNCODE,INVT.PRODUCT_NATURE,INVT.PRODUCT_PACKSIZE [PACKSIZE],  
-- INVT.PRODUCT_CRATE_PACKSIZE [CRATE PACKSIZE],PRODUCT_MRP,PIL.RATE,  
-- PIL.CRATES,PIL.LTR,case when PIL.BasicValue!=0 and PIL.[Remark]!='FOC' then (SELECT BoxQty FROM dbo.udf_GetPCSDetails(PIL.Box,CAST(INVT.PRODUCT_PACKSIZE AS INT))) else 0 end BOXQTY,  
-- case when PIL.BasicValue!=0 and PIL.[Remark]!='FOC' then (SELECT PCSQty FROM dbo.udf_GetPCSDetails(PIL.Box,CAST(INVT.PRODUCT_PACKSIZE AS INT))) else 0 end PCSQty,  
-- case when PIL.BasicValue!=0 and PIL.[Remark]!='FOC' then (SELECT BoxPrint FROM dbo.udf_GetPCSDetails(PIL.Box,CAST(INVT.PRODUCT_PACKSIZE AS INT))) else 0 end [TotalBoxPCS],  
-- case when PIL.BasicValue=0 and PIL.[Remark]='FOC' then PIL.BOX else 0 end FOCQTY,  
-- PIL.BOX TOTALQty, [BASICVALUE],[TRDDISCPERC],[TRDDISCVALUE],[PRICE_EQUALVALUE],  
-- TAX [TAX1%],TAXCOMPONENT [TAX1 COMPONENT],TAXAMOUNT [TAX1 AMT],  
-- ADD_TAX_PERC [TAX2%],ADDTAXCOMPONENT [TAX2 COMPONENT],ADD_TAX_AMOUNT [TAX2 AMT],  
-- PIL.VAT_INC_PERC [TOT TAX%],PIL.VAT_INC_PERCVALUE [TOT TAX AMT],  
-- PIL.[AMOUNT]   
-- FROM ax.ACXPURCHINVRECIEPTLINE PIL     
-- INNER JOIN ax.ACXPURCHINVRECIEPTHEADER PIH ON PIL.PURCH_RECIEPTNO=PIH.DOCUMENT_NO   
-- AND PIL.SITEID=PIH.SITE_CODE  
-- INNER JOIN AX.INVENTTABLE INVT ON PIL.PRODUCT_CODE=INVT.ITEMID     
-- LEFT OUTER JOIN AX.INVENTSITE IV ON PIH.SITE_CODE=IV.SITEID  
   
--  WHERE PIL.SITEID=@Site_Code and PIL.DATAAREAID=@DATAAREAID    
-- AND PIH.[SALE_INVOICEDATE]>= @StartDate and PIH.[SALE_INVOICEDATE]<=@EndDate  --@EndDate    
----order by PIH.DOCUMENT_DATE,PIH.DOCUMENT_NO,PRODUCT    
    
--UNION ALL    
    
--SELECT PIH.SITE_CODE CUSTOMER_CODE,IV.NAME [CUSTOMER NAME],PIL.PURCH_RETURNNO AS PURCH_RECIEPTNO,  
--  PIL.PURCH_RETURNNO as DOCUMENT_NO, CONVERT(nvarchar(20), PIH.PURCH_RETURNDATE,105) as RECEIPTDATE,  
--  GSTINVOICENO,DISTGSTINNO,  
--  CASE WHEN ISNULL(DISTGSTINREGDATE,'1900-01-01')='1900-01-01' THEN '' ELSE CONVERT(NVARCHAR,DISTGSTINREGDATE,106) END DISTGSTINREGDATE,DISTCOMPOSITIONSCHEME,    
--  PIH.PURCH_RECIEPTNO AS SALE_INVOICENO,CONVERT(nvarchar(20), PIH.PURCH_RECIEPTDATE,105) as SALE_INVOICEDATE,  
--  PURCH_INDENTNO='','' PURCH_INDENTDATE,'' [ORDER TYPE],INVT.PRODUCT_GROUP,   
--  PIL.PRODUCT_CODE,(PIL.PRODUCT_CODE +'-'+ INVT.PRODUCT_NAME) PRODUCT,    
--  INVT.PRODUCT_SUBCATEGORY,INVT.HSNCODE,INVT.PRODUCT_NATURE,INVT.PRODUCT_PACKSIZE [PACKSIZE],  
--  INVT.PRODUCT_CRATE_PACKSIZE [CRATE PACKSIZE],INVT.PRODUCT_MRP,PIL.RATE,  
--  -PIL.CRATES,-PIL.LTR,   
--  (SELECT BoxQty FROM dbo.udf_GetPCSDetails(-PIL.Box,CAST(INVT.PRODUCT_PACKSIZE AS INT))) BOXQTY,  
--  (SELECT PCSQty FROM dbo.udf_GetPCSDetails(-PIL.Box,CAST(INVT.PRODUCT_PACKSIZE AS INT)))  PCSQty,  
--  (SELECT BoxPrint FROM dbo.udf_GetPCSDetails(-PIL.Box,CAST(INVT.PRODUCT_PACKSIZE AS INT))) [TotalBoxPCS],  
--  FOCQTY=0, -PIL.BOX as TOTALQty, -[BASICVALUE],[TRDDISCPERC],[TRDDISCVALUE],[PRICE_EQUALVALUE],  
--  TAX [TAX1%],TAXCOMPONENT [TAX1 COMPONENT],-TAXAMOUNT [TAX1 AMT],  
--  ADD_TAX_PERC [TAX2%],ADDTAXCOMPONENT [TAX2 COMPONENT],-ADD_TAX_AMOUNT [TAX2 AMT],  
--  PIL.VAT_INC_PERC [TOT TAX%],-PIL.VAT_INC_PERCVALUE [TOT TAX AMT],  
--  -PIL.[AMOUNT]   
-- FROM [ax].[ACXPURCHRETURNLINE]  PIL     
-- Inner Join [ax].[ACXPURCHRETURNHEADER] PIH on  PIL.Purch_ReturnNo=PIH.Purch_ReturnNo and  PIL.SITEID=PIH.SITE_Code    
-- INNER JOIN AX.INVENTTABLE INVT ON PIL.PRODUCT_CODE=INVT.ITEMID     
-- LEFT OUTER JOIN AX.INVENTSITE IV ON PIH.SITE_CODE=IV.SITEID  
-- WHERE PIL.SITEID=@Site_Code and PIH.Purch_ReturnDate>=@StartDate   
--  and PIH.Purch_ReturnDate<=@EndDate     
    
--order by RECEIPTDATE,DOCUMENT_NO,PRODUCT_Code    
END    