USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[SP_SALEREGISTERINVOICEWISE]    Script Date: 10/7/2019 8:03:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[SP_SALEREGISTERINVOICEWISE]  
(@siteid NVARCHAR(20),  
@begindate DATE,  
@enddate DATE,
@CustomerGroup NVARCHAR(20),
@Customer NVARCHAR(20),
@BUCODE NVARCHAR(10)=''
)  
AS  
BEGIN   

IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
IF LEN(@SITEID)>0                     
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',')   END             

-------BUCODE-------  
   IF OBJECT_ID('tempdb..#tmpBuCode') IS NOT NULL BEGIN DROP TABLE #tmpBuCode  END   
   CREATE TABLE #tmpBuCode (BU_CODE NVARCHAR(10))  
   IF LEN(@BUCODE)>0  
   BEGIN INSERT INTO #tmpBuCode SELECT ID FROM DBO.CommaDelimitedToTable(@BUCODE,',') 
   END  
   ELSE
   BEGIN INSERT INTO #tmpBuCode SELECT BU_CODE FROM AX.ACXSITEBUMAPPING WHERE SITEID IN (SELECT SITEID FROM #TMPSITELIST)  
   END

	SELECT [DIST. CODE] SITEID,[DIST. NAME],BU_CODE [BU CODE], BU_DESC [BU NAME],TRANTYPE,CUST_GROUP_CODE,[CUST GROUP] CUSTGROUP_NAME,CUSTOMER_CODE,CUSTOMER_NAME,INVOICE_NO,[INVOICE DATE] INVOICE_DATE,BOX+[SCHEME BOX] BOX,
		PCS+[SCHEME PCS] PCS, CONVERT(DECIMAL(18,6),CASE WHEN BOXPCS<>'0' THEN [SCHEME BOXPCS] ELSE [BOXPCS] END) [TotalBoxPCS],
		[TOTAL QTY] TotalQtyConv,LTR,(MRP*[TOTAL QTY]) as MRP,[LINE AMOUNT] [LINEAMOUNT],DISC_AMOUNT,[DISC2 AMT] SEC_DISC_AMOUNT,0 SURCHARGE,  
  [TD%] TD_Per,[PE%] [PE_Per],[TD AMT] TDVALUE,[PE AMT] PEValue,[SCHEME DISC AMT] DISC,[TAX1%] [TAX_CODE],[TAX1 AMT] TAX_AMOUNT,[TAX1 COMPONENT],[TAX2 COMPONENT],[TAX2%] ADDTAX_CODE,[TAX2 AMT] ADDTAX_AMOUNT,AMOUNT,SCHEMEDISCVALUE
 
 FROM vw_SaleRegister WHERE [DIST. CODE] IN(SELECT SITEID FROM #TMPSITELIST) AND [INVOICE DATE]>=@begindate AND [INVOICE DATE]<=@EndDate AND 
    [CUST_GROUP_CODE] like case when @CustomerGroup='' then '%' else @CustomerGroup end  
  and CUSTOMER_CODE like case when @Customer='' then '%' else @Customer end
  AND BU_CODE IN (SELECT BU_CODE FROM #tmpBuCode)
END 