USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[Usp_ITEMSKUWISE]    Script Date: 10/7/2019 8:44:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[Usp_ITEMSKUWISE]  
(  
 @SITEID nvarchar(max),  
 @StartDate  SMALLDATETIME,  
 @EndDate SMALLDATETIME,  
 @CUST_GROUP nvarchar(20),  
 @CUSTOMER_NAME nvarchar(40),  
 @PRODUCT_GROUP   nvarchar(40),  
 @PRODUCT_SUBCATEGORY  nvarchar(40),
 @BUCODE NVARCHAR(10)=''
)  
As   
Begin  


IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
IF LEN(@SITEID)>0                     
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',')   END     

-------BUCODE-------  
IF OBJECT_ID('tempdb..#tmpBuCode') IS NOT NULL BEGIN DROP TABLE #tmpBuCode  END   
CREATE TABLE #tmpBuCode (BU_CODE NVARCHAR(MAX))  
IF LEN(@BUCODE)>0  
BEGIN INSERT INTO #tmpBuCode SELECT ID FROM DBO.CommaDelimitedToTable(@BUCODE,',') 
END  
ELSE
BEGIN INSERT INTO #tmpBuCode SELECT BU_CODE FROM AX.ACXSITEBUMAPPING WHERE SITEID  IN (SELECT SITEID FROM #TMPSITELIST)  
END
	
SELECT [DIST. CODE] SITEID,NAMEALIAS,PRODUCT_NAME,CUST_GROUP_CODE [CUST_GROUP],CUSTOMER_NAME,
BU_CODE AS [BU CODE],BU_DESC AS [BU NAME], PRODUCT_GROUP,PRODUCT_SUBCATEGORY,
(BOX + [SCHEME BOX]) BOX,(PCS +[SCHEME PCS]) PC,[TOTAL QTY] TotalQtyConv,LTR,AMOUNT,
CONVERT(DECIMAL(18,6),CASE WHEN BOXPCS<>'0' THEN [BOXPCS] ELSE [SCHEME BOXPCS] END) [TotalBoxPCS]
FROM VW_SALEREGISTER
WHERE [DIST. CODE]  IN (SELECT SITEID FROM #TMPSITELIST)  AND [INVOICE DATE]>=@StartDate AND [INVOICE DATE]<=@EndDate 
AND CUST_GROUP_CODE LIKE CASE WHEN @CUST_GROUP='' THEN '%' ELSE @CUST_GROUP END
AND PRODUCT_GROUP LIKE CASE WHEN @PRODUCT_GROUP='' THEN '%' ELSE @PRODUCT_GROUP END
AND PRODUCT_SUBCATEGORY LIKE CASE WHEN @PRODUCT_SUBCATEGORY ='' THEN '%' ELSE @PRODUCT_SUBCATEGORY  END
AND CUSTOMER_CODE LIKE CASE WHEN @CUSTOMER_NAME ='' THEN '%' ELSE @CUSTOMER_NAME END
AND BU_CODE IN (SELECT BU_CODE FROM #tmpBuCode)
ORDER BY NAMEALIAS ASC

--select ASS.SITEID, ASS.NAMEALIAS, ASS.PRODUCT_NAME,c.CUST_GROUP, c.CUSTOMER_NAME,INVT.PRODUCT_GROUP,INVT.PRODUCT_SUBCATEGORY, BOXQTY as BOX,  
-- PCSQTY as PC, isnull(BOXPCS,'0') as [TotalBoxPCS]   
--,BOX as TotalQtyConv, ASS.LTR, AMOUNT from ACX_SKUWISE_SALE ASS INNER JOIN AX.INVENTTABLE INVT ON ASS.PRODUCT_CODE=INVT.ITEMID  
--INNER JOIN ax.acxcustmaster C on ASS.SITEID=c.SITE_CODE      
--where SITEID = @SITEID and INVOICE_DATE >=  @StartDate and  INVOICE_DATE <=@EndDate and   
-- CUST_GROUP like case when @CUST_GROUP=''then '%' else @CUST_GROUP end  
-- and CUSTOMER_NAME like case when  @CUSTOMER_NAME =''then '%' else @CUSTOMER_NAME end  
-- and PRODUCT_GROUP like case when @PRODUCT_GROUP=''then '%' else @PRODUCT_GROUP end  
-- and PRODUCT_SUBCATEGORY like case when @PRODUCT_SUBCATEGORY =''then '%' else @PRODUCT_SUBCATEGORY  end   
--ORDER BY NAMEALIAS ASC   
end  