USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_USP_REACHREPORT]    Script Date: 12/24/2019 6:22:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--EXEC ACX_USP_REACHREPORT '0000602544','2018-04-01','0','0000602544'  

ALTER PROCEDURE [dbo].[ACX_USP_REACHREPORT] (@SITEID NVARCHAR(MAX),@MONTHYEAR SMALLDATETIME,@UserType int,@UserCode nvarchar(20))  
AS   
BEGIN  
IF OBJECT_ID('TEMPDB..#TMPCHNGROUP') IS NOT NULL BEGIN DROP TABLE #TMPCHNGROUP END 
CREATE TABLE #TMPCHNGROUP (CHANNELGROUPCODE NVARCHAR(50)); 
IF (@UserType != 3)
BEGIN   INSERT INTO #TMPCHNGROUP SELECT DISTINCT cust_group FROM AX.ACXCUSTMASTER  END
ELSE 
BEGIN	INSERT INTO #TMPCHNGROUP SELECT CHANNELGROUPCODE FROM DBO.UDF_GETCHANNELGROUPBYUSER(@UserCode)  END 

IF OBJECT_ID('TEMPDB..#tmpsite') IS NOT NULL BEGIN DROP TABLE #tmpsite END
CREATE TABLE #tmpsite (SITEID NVARCHAR(50));          
IF LEN(@SITEID)>0           
BEGIN	INSERT INTO #tmpsite  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',') 		END
ELSE IF (@UserType != 3)
BEGIN	INSERT INTO #tmpsite select SITEID from AX.InventSite WHERE LEN(SITEID)>0	END 
ELSE 
BEGIN	INSERT INTO #tmpsite SELECT Distinct DISTRIBUTOR  FROM DBO.UDF_GetSALESHIERARCHY(@UserCode)  END

SELECT *,round((Case when Outlet<=0 then convert(decimal,0) else convert(decimal,Reach)/convert(decimal,outlet) end) *100,2) [Reach_Per] ,
CAST(CASE WHEN BILL<>0 THEN BILLAMOUNT/BILL ELSE 0 END AS DECIMAL(18,2)) AS VALUEPERBILL 
FROM (
	SELECT S.SITEID,S.NAME,PLM.PSRCODE,PM.PSR_NAME,BM.BEATCODE,BM.BeatName  
	,(SELECT COUNT(Customer_Code) 
		FROM AX.ACXCUSTMASTER CM   
		WHERE CM.PSR_CODE=PLM.PSRCODE AND CM.PSR_BEAT=BM.BEATCODE AND S.SITEID=CM.SITE_CODE AND CM.BLOCKED = 0
	) OUTLET
	,(SELECT COUNT(Customer_code) 
		FROM (Select DISTINCT CUSTOMER_CODE from vw_saleregister V where V.[DIST. CODE]=S.SITEID 
				AND V.[PSR_CODE]=PLM.PSRCODE AND V.[PSR_BEAT]=BM.BEATCODE AND MONTH(V.[INVOICE DATE])=MONTH(@MONTHYEAR) and YEAR([INVOICE DATE])=YEAR(@MONTHYEAR)
				)AA
	)AS REACH  

	,ISNULL((SELECT SUM(CASE WHEN TRANTYPE='Sale Reversal' THEN -1 ELSE 1 END) 
	 FROM (Select DISTINCT TRANTYPE,INVOICE_NO from vw_saleregister V where V.[DIST. CODE]=S.SITEID 
	 AND V.[PSR_CODE]=PLM.PSRCODE AND V.[PSR_BEAT]=BM.BEATCODE AND MONTH(V.[INVOICE DATE])=MONTH(@MONTHYEAR) and YEAR([INVOICE DATE])=YEAR(@MONTHYEAR)
	 ) AA),0) AS BILL

	,CAST(ISNULL((SELECT SUM(SO_VALUE) FROM AX.ACXSALESHEADER WHERE   

	MONTH(SO_DATE)=MONTH(@MONTHYEAR) AND YEAR(SO_DATE)=YEAR(@MONTHYEAR)

	AND SITEID=S.SITEID AND CUSTOMER_CODE IN   

	(SELECT CM.CUSTOMER_CODE FROM AX.ACXCUSTMASTER CM   

	WHERE CM.PSR_CODE=PLM.PSRCODE AND CM.PSR_BEAT=BM.BEATCODE AND S.SITEID=CM.SITE_CODE AND CM.BLOCKED = 0)  

	),0) AS DECIMAL(18,2)) AS ORDERAMOUNT  

	,CAST(ISNULL((Select SUM(AMOUNT) from vw_saleregister V where V.[DIST. CODE]=S.SITEID 
	 AND V.[PSR_CODE]=PLM.PSRCODE AND V.[PSR_BEAT]=BM.BEATCODE AND MONTH(V.[INVOICE DATE])=MONTH(@MONTHYEAR) and YEAR([INVOICE DATE])=YEAR(@MONTHYEAR)
	 ),0) AS DECIMAL(18,2)) AS BILLAMOUNT   


FROM AX.INVENTSITE S  

JOIN AX.ACXPSRSITELinkingMaster PLM ON S.SITEID=PLM.SITE_CODE  

JOIN AX.ACXPSRMaster PM ON PM.PSR_CODE=PLM.PSRCODE   

JOIN AX.ACXPSRBEATMASTER BM ON BM.PSRCODE=PM.PSR_CODE   

AND BM.SITE_CODE=S.SITEID  

WHERE S.SITEID IN (SELECT SITEID FROM #tmpsite)) AA  

END
