USE [7200]
GO
/****** Object:  StoredProcedure [dbo].[ACX_USP_KEYCUSTOMERSALEREPORT]    Script Date: 1/1/2020 10:43:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ACX_USP_KEYCUSTOMERSALEREPORT]          
(@FROMDATE smalldatetime ,@TODATE smalldatetime,@SITEID nvarchar(max),@UserCode nvarchar(50)='',@UserType nvarchar(50)='',
@BUCODE NVARCHAR(10)='')  AS          
IF OBJECT_ID('TEMPDB..#TMPCHNGROUP') IS NOT NULL BEGIN DROP TABLE #TMPCHNGROUP END              
CREATE TABLE #TMPCHNGROUP (CHANNELGROUPCODE NVARCHAR(50));            
IF (@UserType != 3)            
BEGIN   INSERT INTO #TMPCHNGROUP SELECT DISTINCT CUST_GROUP FROM AX.ACXCUSTMASTER  
END          
ELSE       

   
BEGIN  INSERT INTO #TMPCHNGROUP SELECT CHANNELGROUPCODE FROM DBO.UDF_GETCHANNELGROUPBYUSER(@UserCode)  END          

IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(50));  


        
IF LEN(@SITEID)>0           
BEGIN	INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',') 		END
ELSE IF (@UserType != 3)
BEGIN	INSERT INTO #TMPSITELIST select SITEID from AX.InventSite WHERE LEN(SITEID)>0	END 
ELSE 
BEGIN
INSERT INTO #TMPSITELIST SELECT Distinct DISTRIBUTOR  FROM DBO.UDF_GetSALESHIERARCHY(@UserCode)		END

-------BUCODE-------  
IF OBJECT_ID('tempdb..#tmpBuCode') IS NOT NULL BEGIN DROP TABLE #tmpBuCode  END   
CREATE TABLE #tmpBuCode (BU_CODE NVARCHAR(10))  
IF LEN(@BUCODE)>0  
BEGIN INSERT INTO #tmpBuCode SELECT ID FROM DBO.CommaDelimitedToTable(@BUCODE,',') 
END  
ELSE
BEGIN INSERT INTO #tmpBuCode SELECT DISTINCT BU_CODE FROM AX.ACXSITEBUMAPPING WHERE SITEID IN (SELECT SITEID FROM #TMPSITELIST)           
END
           
BEGIN              
SELECT Row_Number() over (Order By CM.SITE_CODE,CM.CUSTOMER_NAME) as SRLNO, CM.SITE_CODE,S.NAME [SITE_NAME],BU_CODE [BU CODE],BU_DESC [BU NAME],CM.CUSTOMER_CODE,CM.CUSTOMER_NAME,          
CM.ADDRESS1 +  CASE WHEN LEN(CM.ADDRESS2)>0 THEN  ', ' + CM.ADDRESS2 ELSE '' END  + CASE WHEN LEN(CM.CITY )>0 THEN  ', ' + CM.CITY  ELSE '' END          
+ CASE WHEN LEN(CM.ZIPCODE )>0 THEN  '-' + CM.ZIPCODE  ELSE '' END + CASE WHEN LEN(CM.STATE )>0 THEN  ', ' + CM.STATE  ELSE '' END AS [ADDRESS],      
ISNULL(SUM(BOX+[SCHEME BOX]),0) BOX,ISNULL(SUM([SCHEME PCS]+PCS),0) PCS,SUM([TOTAL QTY]) TotalQtyConv,ISNULL(SUM(LTR),0) LTR,ISNULL(SUM(AMOUNT),0) INVOICE_VALUE,      
ISNULL(SUM(CONVERT(DECIMAL(18,6),CASE WHEN BOXPCS<>'0' THEN [BOXPCS] ELSE [SCHEME BOXPCS] END)),0) [TotalBoxPCS],        
COUNT(DISTINCT INVOICE_NO) NO_OF_INVOICE      
FROM AX.ACXCUSTMASTER CM JOIN AX.INVENTSITE S ON S.SITEID=CM.SITE_CODE      
LEFT OUTER JOIN VW_SALEREGISTER SR ON SR.[DIST. CODE]=CM.SITE_CODE AND SR.
[DIST. CODE]=S.SITEID AND SR.CUSTOMER_CODE=CM.CUSTOMER_CODE      
WHERE KEY_CUSTOMER=1 AND ((CM.CLOSING_DATE > @FROMDATE AND CM.CLOSING_DATE > @TODATE) OR CM.BLOCKED != 1)
AND CM.SITE_CODE IN (SELECT SITEID FROM #TMPSITELIST)           
AND CM.[CUST_GROUP] IN (SELECT CHANNELGROUPCODE FROM #TMPCHNGROUP)        
and [INVOICE DATE]>= @FROMDATE and [INVOICE DATE]<=@TODATE  
AND BU_CODE IN (SELECT BU_CODE FROM #tmpBuCode)
GROUP BY CM.SITE_CODE,CM.CUSTOMER_NAME,S.NAME,CM.CUSTOMER_CODE,BU_CODE,BU_DESC ,
CM.ADDRESS1 +  CASE WHEN LEN(CM.ADDRESS2)>0 THEN  ', ' + CM.ADDRESS2 ELSE '' END  + CASE WHEN LEN(CM.CITY )>0 THEN  ', ' + CM.CITY  ELSE '' END          
+ CASE WHEN LEN(CM.ZIPCODE )>0 THEN  '-' + CM.ZIPCODE  ELSE '' END + CASE WHEN LEN(CM.STATE )>0 THEN  ', ' + 
CM.STATE  ELSE '' END      
END