USE [7200]
GO
/****** Object:  StoredProcedure [ax].[ACX_MonthlySummerySheet_CLAIM]    Script Date: 11/12/2019 8:21:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--EXEC [ax].[ACX_MonthlySummerySheet_CLAIM] @SITEID='000059144',@SITESTATE='DL',@StartDate='2010-09-01',@EndDate='2019-01-31'                      

ALTER Procedure [ax].[ACX_MonthlySummerySheet_CLAIM] (@SITEID nVarchar(max)='',@SITESTATE nVarchar(50)='',@StartDate smalldatetime,@EndDate smalldatetime,@BUCODE NVARCHAR(10)='') AS              

BEGIN      
        
IF OBJECT_ID('tempdb..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END       
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20))      
IF LEN(@SiteId)>0      
BEGIN INSERT INTO #TMPSITELIST SELECT ID FROM DBO.CommaDelimitedToTable(@SiteId,',') END        


IF OBJECT_ID('TEMPDB..#TMPCAT') IS NOT NULL BEGIN DROP TABLE #TMPCAT END              

CREATE TABLE #TMPCAT (STATECODE NVARCHAR(50),SITEID NVARCHAR(50),CATEGORY NVARCHAR(100),SUBCATEGORY NVARCHAR(150),BOX FLOAT,LTR FLOAT,CLAIM_AMOUNT FLOAT,Description nvarchar(100))              

PRINT GETDATE()              

INSERT INTO #TMPCAT EXEC [ax].[ACX_MonthySummarySheet_Discount] @StartDate,@EndDate,@SiteId,@BUCODE                    

PRINT GETDATE()                

UPDATE [ax].[ACXCLAIMMASTER] SET CLAIM_MONTH=FROM_DATE WHERE CLAIM_MONTH IS NULL                    

INSERT INTO #TMPCAT  SELECT  (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE),@SITEID,TC.NAME AS CATEGORY_NAME,TSC.NAME AS SUB_CATEGORY_NAME,                

0 AS Box,0 AS LTR,ROUND((SELECT ISNULL(SUM(ACTUAL_INCENTIVE),0) FROM [ax].[ACXCLAIMMASTER] CM WHERE CM.CLAIM_CATEGORY=TSC.CATEGORY AND CM.CLAIM_SUBCATEGORY=TSC.SUBCATEGORY                    

AND SITE_CODE IN (SELECT SITEID FROM #TMPSITELIST) AND CM.CLAIM_MONTH>=@STARTDATE AND CM.CLAIM_MONTH<=@ENDDATE),2) CLAIM_AMOUNT,(SELECT TOP 1 TARGET_DESCRIPTION FROM [ax].[ACXCLAIMMASTER] CM                 

WHERE CM.CLAIM_CATEGORY=TSC.CATEGORY AND CM.CLAIM_SUBCATEGORY=TSC.SUBCATEGORY AND SITE_CODE IN (SELECT SITEID FROM #TMPSITELIST) AND CM.CLAIM_MONTH>=@STARTDATE AND CM.CLAIM_MONTH<=@ENDDATE )                    

FROM AX.ACXTARGETCATEGORY TC JOIN AX.ACXTARGETSUBCATEGORY TSC ON TSC.CATEGORY=TC.CATEGORY --WHERE TSC.SUBCATEGORY NOT IN ('TG017','TG018','TG019','TG035','TG036','TG037','TG020','TG029','TG052','TG027')                    

ORDER BY TC.CATEGORY,TSC.SUBCATEGORY                    

  

PRINT GETDATE()                  

--Scheme Data                      

IF @StartDate>='2017-07-01'                

BEGIN                

IF OBJECT_ID('TEMPDB..#TMPSchemeEXP') IS NOT NULL BEGIN DROP TABLE #TMPSchemeEXP END                    

Create table #TMPSchemeEXP (SITECODE NVARCHAR(20),SITENAME NVARCHAR(200),CUSTGROUP_NAME NVARCHAR(200),CUSTOMERCODE NVARCHAR(20),CUSTOMER_NAME NVARCHAR(350),                

DOCTYPE NVARCHAR(250),INVOICE_NO NVARCHAR(20),INVOIC_DATE SMALLDATETIME,REFDOC NVARCHAR(max),REFDOCDATE SMALLDATETIME,INVOICE_VALUE DECIMAL(18,6),SchemeCode NVARCHAR(50),              

SCHEMEDESC NVARCHAR(300),SCHEMETYPE NVARCHAR(50),SLAB DECIMAL(10,4),SLABTYPE NVARCHAR(50),SHCEMEON DECIMAL(10,4),SCHEMEBASED NVARCHAR(50),            

PRODUCT_GROUP NVARCHAR(100),PRODUCT_CODE NVARCHAR(250),PRODUCT_NAME NVARCHAR(250),BASICRATE DECIMAL(18,4), BOX DECIMAL(18,6),LTR DECIMAL(18,6),BASICVALUE DECIMAL(18,6),ADDSCHAMT DECIMAL(18,6),SCHEMEAMT DECIMAL(18,6),TOTALEXP DECIMAL(18,6))              

--exec ax.ACX_SCHEMECLAIMREPORT '2017-08-01','2017-08-31','','0000601795','','','BU1'                    

  

INSERT INTO #TMPSchemeEXP exec ax.ACX_SCHEMECLAIMREPORT @STARTDATE,@ENDDATE,'',@SITEID,'','',@BUCODE                      

PRINT 'GET SCHEME DATA'                

PRINT GETDATE()                

 

INSERT INTO #TMPCAT                       

SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE),@SITEID,(SELECT NAME FROM AX.ACXTARGETCATEGORY                     

WHERE CATEGORY='TG04'),(SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG020') +'-AUTO', --'Market Scheme - ICE CREAM',                    

SUM(A.BOX) BOX,SUM(A.LTR) LTR,SUM(SCHEMEAMT+ADDSCHAMT) AMOUNT,'' AS [Description] FROM #TMPSchemeEXP A                    

WHERE PRODUCT_GROUP! ='FROZEN'              

 --Inner Join [ax].[INVENTTABLE] C on C.ITEMID=A.[PRODUCT_CODE] WHERE C.[PRODUCT_GROUP]! ='FROZEN' --AND LEN(A.[PRODUCT_CODE])>0                 



INSERT INTO #TMPCAT              

SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE) ,@SITEID,(SELECT NAME FROM AX.ACXTARGETCATEGORY                     

WHERE CATEGORY='TG04'),(SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG029')+'-AUTO', --'Market Scheme - Frozen',                    

SUM(A.BOX) BOX,SUM(A.LTR) LTR,SUM(SCHEMEAMT+ADDSCHAMT) AMOUNT,'' AS [Description] FROM #TMPSchemeEXP A               

WHERE PRODUCT_GROUP ='FROZEN'              

  --Inner Join [ax].[INVENTTABLE] C on C.ITEMID=A.[PRODUCT_CODE]  WHERE C.[PRODUCT_GROUP] ='FROZEN' --AND LEN(A.[PRODUCT_CODE])>0                    

END                

ELSE                

BEGIN                

IF OBJECT_ID('TEMPDB..#TMPScheme1') IS NOT NULL BEGIN DROP TABLE #TMPScheme1 END                      

Create table #TMPScheme1 (INVOICE_NO NVARCHAR(20),SchemeCode NVARCHAR(50),SITEID NVARCHAR(20),Name NVARCHAR(250),CUSTOMER_CODE NVARCHAR(20),CUSTOMER_NAME NVARCHAR(250),                

CUSTGROUP_NAME NVARCHAR(150),PRODUCT_CODE NVARCHAR(250),PRODUCT_NAME NVARCHAR(250),INVOIC_DATE SMALLDATETIME,INVOICE_VALUE FLOAT, BOX FLOAT,LTR FLOAT,RATE FLOAT,                

AMOUNT FLOAT,TAXAMOUNT FLOAT,NONSCHEMEAMT FLOAT,SCHEMEAMT FLOAT,SchemeName NVARCHAR(150))                



INSERT INTO #TMPScheme1 exec ax.ACX_PartyWiseSchemeDetailsonPurchaseRaterReport @STARTDATE,@ENDDATE ,@SITEID,'',''                  

PRINT 'GET SCHEME DATA'                

PRINT GETDATE()                

INSERT INTO #TMPCAT SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE),@SITEID,(SELECT NAME FROM AX.ACXTARGETCATEGORY                     

WHERE CATEGORY='TG04'),(SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG020')+'-AUTO', --'Market Scheme - ICE CREAM',                    

SUM(A.BOX) BOX,SUM(A.LTR) LTR,SUM(SCHEMEAMT) AMOUNT,'' AS [Description] FROM #TMPScheme1 A Inner Join [ax].[INVENTTABLE] C on C.ITEMID=A.[PRODUCT_CODE]  AND C.BU_CODE LIKE CASE WHEN LEN(@BUCODE)>0 THEN @BUCODE ELSE '%' END            

WHERE C.[PRODUCT_GROUP]! ='FROZEN' AND LEN(A.[PRODUCT_CODE])>0                    

      

INSERT INTO #TMPCAT SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE) ,@SITEID,(SELECT NAME FROM AX.ACXTARGETCATEGORY                       

WHERE CATEGORY='TG04'),(SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG029')+'-AUTO', --'Market Scheme - Frozen',                

SUM(A.BOX) BOX,SUM(A.LTR) LTR,SUM(SCHEMEAMT) AMOUNT,'' AS [Description] FROM #TMPScheme1 A Inner Join [ax].[INVENTTABLE] C on C.ITEMID=A.[PRODUCT_CODE]  AND C.BU_CODE LIKE CASE WHEN LEN(@BUCODE)>0 THEN @BUCODE ELSE '%' END        

WHERE C.[PRODUCT_GROUP] ='FROZEN' AND LEN(A.[PRODUCT_CODE])>0                    



END                  

PRINT 'SCHEME INSERTED'                

PRINT GETDATE()                

IF OBJECT_ID('TEMPDB..#TMPSpecialRateClaim') IS NOT NULL BEGIN DROP TABLE #TMPSpecialRateClaim END                    

Create table #TMPSpecialRateClaim (SITEID NVARCHAR(20),Name NVARCHAR(250),CUSTOMER_CODE NVARCHAR(20),CUSTOMER_NAME NVARCHAR(250),PRODUCT_CODE NVARCHAR(20),PRODUCT_NAME NVARCHAR(250),                    

CUST_GROUP NVARCHAR(15),CUSTGROUP_NAME NVARCHAR(150),MRP FLOAT,BOX FLOAT,LTR FLOAT,RP_RATES FLOAT,DIFF FLOAT,EXPENSE FLOAT)                    

PRINT 'SPECIAL CLAIM'                  

PRINT GETDATE()                

INSERT INTO #TMPSpecialRateClaim exec [ax].[ACX_SpecialRatesClaimReport] @STARTDATE,@ENDDATE,'',@SITEID,'',@BUCODE                    



PRINT 'GET SPECIAL CLAIM'                  

PRINT GETDATE()                



INSERT INTO #TMPCAT                   

SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE),@SITEID,(SELECT NAME FROM AX.ACXTARGETCATEGORY WHERE CATEGORY='TG04'),                

(SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG052')+'-AUTO', --'Market Scheme - ICE CREAM',                      

SUM(A.BOX) BOX,SUM(A.LTR) LTR,SUM(EXPENSE) AMOUNT,'' AS [Description] FROM #TMPSpecialRateClaim A                 



PRINT 'SPECIAL CLAIM INSERTED'                 

PRINT GETDATE()                  

--FOC Data           

 --MARKET PROMOTION              

IF @StartDate>='2017-07-01'                 

BEGIN                

INSERT INTO #TMPCAT          

SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE) ,@SITEID,(SELECT NAME FROM AX.ACXTARGETCATEGORY WHERE CATEGORY='TG04'),                

(SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG027')+'-AUTO',--'Sampling -  Taste & Trial',                    

SUM(box) BOX,SUM(ltr) LTR,SUM(AMOUNT) AMOUNT,'' as [Description] FROM               

(SELECT CAST(ISNULL(((CASE WHEN B.TRANTYPE=2 THEN -A.Box ELSE A.BOX END)),0) as decimal(18,2)) as Box,                    

CAST(ISNULL(((CASE WHEN B.TRANTYPE=2 THEN -A.LTR ELSE A.LTR END)),0) as decimal(18,2)) as Ltr,              

Amount =A.CLAIM_DISC_AMT * (CASE WHEN B.TRANTYPE=2 THEN -1 ELSE 1 END)                  

FROM [ax].[ACXSALEINVOICELINE] A INNER JOIN [ax].[ACXSALEINVOICEHEADER] B ON A.INVOICE_NO=B.INVOICE_NO and A.Siteid=B.Siteid AND A.[CUSTOMER_CODE]=B.[CUSTOMER_CODE]                 

and A.[DATAAREAID]=B.[DATAAREAID] Inner Join [ax].[INVENTTABLE] C on C.ITEMID=A.[PRODUCT_CODE] AND C.BU_CODE LIKE CASE WHEN LEN(@BUCODE)>0 THEN @BUCODE ELSE '%' END              

Where A.[SITEID] IN (SELECT SITEID FROM #TMPSITELIST) and B.[INVOIC_DATE]>=@STARTDATE AND B.[INVOIC_DATE]<=@ENDDATE and B.CUSTGROUP_CODE='CG0006'                    

) AB                     

END              

ELSE 

begin              

INSERT INTO #TMPCAT                

SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE) ,@SITEID,(SELECT NAME FROM AX.ACXTARGETCATEGORY WHERE CATEGORY='TG04'),                

(SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG027')+'-AUTO',--'Sampling -  Taste & Trial',                      

SUM(box) BOX,SUM(ltr) LTR,SUM(AMOUNT) AMOUNT,'' as [Description] FROM (SELECT a.invoice_no,line_no,cast(isnull((A.tax_code + (CASE WHEN ADDITIONALTAXBASIS=0 THEN ROUND((A.tax_code * A.ADDTAX_CODE/100),2)                     

ELSE A.ADDTAX_CODE END) ),0) as decimal(18,2)) as tax,CAST(ISNULL(((CASE WHEN B.TRANTYPE=2 THEN -A.Box ELSE A.BOX END)),0) as decimal(18,2)) as Box,                    

CAST(ISNULL(((CASE WHEN B.TRANTYPE=2 THEN -A.LTR ELSE A.LTR END)),0) as decimal(18,2)) as Ltr,                

--Amount=(Select coalesce(cast(Amount as decimal(10,2)),0) * (CASE WHEN B.TRANTYPE=2 THEN -A.Box ELSE A.BOX END) FROM [dbo].[ACX_UDF_GETPRICE](b.invoic_date,D.PriceGroup,A.product_Code))                    

Amount =A.BASEPRICE * (CASE WHEN B.TRANTYPE=2 THEN -A.Box ELSE A.BOX END)                  

FROM [ax].[ACXSALEINVOICELINE] A INNER JOIN [ax].[ACXSALEINVOICEHEADER] B ON A.INVOICE_NO=B.INVOICE_NO and A.Siteid=B.Siteid AND A.[CUSTOMER_CODE]=B.[CUSTOMER_CODE]                 

and A.[DATAAREAID]=B.[DATAAREAID] Inner Join [ax].[INVENTTABLE] C on C.ITEMID=A.[PRODUCT_CODE] AND C.BU_CODE LIKE CASE WHEN LEN(@BUCODE)>0 THEN @BUCODE ELSE '%' END left join VW_CUSTOMERMASTER_HISTORY D on 

D.Customer_Code=B.Customer_Code AND D.SITE_CODE= A.[SITEID]             

Where A.[SITEID] IN (SELECT SITEID FROM #TMPSITELIST) and B.[INVOIC_DATE]>=@STARTDATE AND B.[INVOIC_DATE]<=@ENDDATE --and D.Cust_Group='CG0006'                    

AND A.TRANTYPE=3 ) AB                     

END  

PRINT 'FOC INSERTED'                

PRINT GETDATE()                

PRINT 'VRS SPECIAL DISCOUNT CLAIM'    

INSERT INTO #TMPCAT                     

SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE),@SITEID,    

(SELECT NAME FROM AX.ACXTARGETCATEGORY WHERE CATEGORY='TG03'),                

ISNULL((SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG053'),'')+ '-' + ISNULL(P.NAME,''),    

SUM([TOTAL QTY]) BOX,SUM(LTR) LTR,SUM(([PURCH RATE] * [TOTAL QTY])-[LINE AMOUNT]) AMOUNT,'' AS [Description] FROM     

VW_SALEREGISTER SR      

LEFT OUTER JOIN AX.PRICEDISCGROUP P ON SR.PRICEGROUP=P.GROUPID            

WHERE [INVOICE DATE]>'2019-01-01'  AND [INVOICE DATE]>=@STARTDATE AND [INVOICE DATE]<=@ENDDATE AND [DIST. CODE] IN (SELECT SITEID FROM #TMPSITELIST)    

AND PRODUCT_GROUP IN ('IMPULSE','TAKE HOME') AND  LEN(SCHEMECODE)=0  

AND SR.CUST_GROUP_CODE IN (SELECT CUSTGROUP FROM AX.ACXCUSTGROUPREPORTMAPPINGTABLE WHERE REPORTNAME='M160' AND BLOCKED=0)    

GROUP BY P.NAME    

  

SELECT ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY SUBCATEGORY) AS SRL,CATEGORY,CATEGORY CATEGORY_NAME,SUBCATEGORY,SUBCATEGORY SUB_CATEGORY_NAME,                  

BOX,LTR,CLAIM_AMOUNT,isnull([Description],'') [Description] FROM #TMPCAT WHERE CLAIM_AMOUNT>0 ORDER BY CATEGORY,SUBCATEGORY        

END 