USE [7200]
GO
/****** Object:  StoredProcedure [ax].[ACX_VRS_MonthlySummerySheet_CLAIM]    Script Date: 11/2/2019 10:17:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [ax].[ACX_VRS_MonthlySummerySheet_CLAIM]
(@SITEID nVarchar(max)='',@SITESTATE nVarchar(50)='', 
@StartDate smalldatetime,@EndDate smalldatetime,@VRSCode nVarchar(50)='',@BUCODE NVARCHAR(10)='') AS 
BEGIN

IF OBJECT_ID('TEMPDB..#TMPSITELIST') IS NOT NULL BEGIN DROP TABLE #TMPSITELIST END          
CREATE TABLE #TMPSITELIST (SITEID NVARCHAR(20));                    
IF LEN(@SITEID)>0                     
BEGIN INSERT INTO #TMPSITELIST  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',')   END  


IF OBJECT_ID('TEMPDB..#TMPCAT') IS NOT NULL BEGIN DROP TABLE #TMPCAT END
CREATE TABLE #TMPCAT (STATECODE NVARCHAR(50),SITEID NVARCHAR(50),CATEGORY NVARCHAR(100)
	,SUBCATEGORY NVARCHAR(150),BOX FLOAT,LTR FLOAT,CLAIM_AMOUNT FLOAT,
	Description nvarchar(100))

UPDATE [ax].[ACX_VRSCLAIMMASTER] SET CLAIM_MONTH=FROM_DATE WHERE CLAIM_MONTH IS NULL

INSERT INTO #TMPCAT 

SELECT (SELECT UPPER(LS.Name) FROM [ax].[LOGISTICSADDRESSSTATE] LS WHERE LS.STATEID = @SITESTATE),
	@SITEID,TC.NAME AS CATEGORY_NAME,TSC.NAME AS SUB_CATEGORY_NAME
	,0 AS Box
	,0 AS LTR
	,ROUND((SELECT ISNULL(SUM(ACTUAL_INCENTIVE),0) FROM [ax].[ACX_VRSCLAIMMASTER] CM 
			WHERE CM.CLAIM_CATEGORY=TSC.CATEGORY 
				AND CM.CLAIM_SUBCATEGORY=TSC.SUBCATEGORY
				AND SITE_CODE IN (SELECT SITEID FROM #TMPSITELIST) AND CM.CLAIM_MONTH>=@STARTDATE 
				AND CM.CLAIM_MONTH<=@ENDDATE AND VRS_CODE=@VRSCode
				AND CM.BUCODE LIKE CASE WHEN LEN(@BUCODE)>0 THEN @BUCODE ELSE '%' END
		),2) CLAIM_AMOUNT
	,''
	FROM  AX.ACXTARGETCATEGORY TC 
		JOIN AX.ACXTARGETSUBCATEGORY TSC ON TSC.CATEGORY=TC.CATEGORY
	WHERE TSC.SUBCATEGORY IN ('TG012','TG015','TG010','TG014','TG013','TG022',
	'TG016','TG009','TG032','TG011','TG050','TG051','TG046','TG047','TG044','TG048','TG049','TG045')
	ORDER BY TC.CATEGORY,TSC.SUBCATEGORY

SELECT ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY SUBCATEGORY) AS SRL,
	CATEGORY,CATEGORY CATEGORY_NAME,SUBCATEGORY,SUBCATEGORY SUB_CATEGORY_NAME,
	BOX,LTR,CLAIM_AMOUNT,isnull([Description],'') [Description]
FROM #TMPCAT 
ORDER BY CATEGORY,SUBCATEGORY
END
