USE [7200]
GO
/****** Object:  StoredProcedure [ax].[ACX_MonthySummarySheet_Discount]    Script Date: 11/12/2019 9:07:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--exec [ax].[ACX_MonthySummarySheet_Discount] '01-AUG-2017','31-AUG-2017','0000601795'    
ALTER Procedure [ax].[ACX_MonthySummarySheet_Discount]    
(@FromDate smalldatetime,@ToDate smalldatetime,@SiteId Varchar(max),@BUCODE NVARCHAR(10)='')    
AS     
BEGIN    
SET NOCOUNT ON;   

IF OBJECT_ID('TEMPDB..#TMPSITELISTS') IS NOT NULL BEGIN DROP TABLE #TMPSITELISTS END          
CREATE TABLE #TMPSITELISTS (SITEID NVARCHAR(20));                    
IF LEN(@SITEID)>0                     
BEGIN INSERT INTO #TMPSITELISTS  SELECT ID FROM DBO.CommaDelimitedToTable(@SITEID,',')   END  

 
IF OBJECT_ID('TEMPDB..#TMPTBL') IS NOT NULL BEGIN DROP TABLE #TMPTBL END    
SELECT STATECODE,SITEID,PRODUCT_GROUP,SUM(BOX) QTY,SUM(LTR) LTR,    
 SUM(TDVALUE) TDVALUE,SUM(DISC_AMOUNT) DISC_AMOUNT, SUM(SEC_DISC_AMOUNT) SEC_DISC_AMOUNT,    
 SUM(DISC) DISC INTO #TMPTBL     
 FROM    
  (SELECT UPPER(LS.Name) as STATECODE,SIH.SITEID,CUS.CUST_GROUP,    
   CUSTGROUP_NAME,SIH.CUSTOMER_CODE,CUS.CUSTOMER_NAME,    
   (CASE WHEN INVT.PRODUCT_GROUP='BULK' AND SIL.DISCTYPE=0     
    AND SIL.disccalculationbase=1     
   THEN (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG018') -- 'DISCOUNT ' + INVT.PRODUCT_GROUP + '-VARIABLE-MRP'     
   WHEN INVT.PRODUCT_GROUP='BULK' AND SIL.DISCTYPE=0     
    AND SIL.disccalculationbase=0    
   THEN (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG019') --'DISCOUNT ' + INVT.PRODUCT_GROUP + '-VARIABLE-SALE PRICE'     
   WHEN INVT.PRODUCT_GROUP='BULK' AND SIL.DISCTYPE=1     
   THEN (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG017') --'DISCOUNT ' + INVT.PRODUCT_GROUP + '-FIX'    
   ELSE     
    (CASE WHEN SIL.DISCTYPE=0 AND SIL.disccalculationbase=1     
    THEN (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG036') --'DISCOUNT IMP, TH & ALL-VARIABLE-MRP'     
    WHEN SIL.DISCTYPE=0 AND SIL.disccalculationbase=0    
    THEN (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG037') --'DISCOUNT IMP, TH & ALL-VARIABLE-SALE PRICE'     
    ELSE (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG035') --'OTHER THAN BULK-FIX'    
    END)     
   END) AS PRODUCT_GROUP,SIH.INVOIC_DATE AS INVOICE_DATE,    
   CASE SIH.TRANTYPE WHEN 1 THEN 'SL' WHEN 2 THEN 'SR' END AS TRANSTYPE,    
   SIH.INVOICE_NO ,SIL.PRODUCT_CODE,INVT.PRODUCT_NAME, INVT.FLAVOUR,    
   INVT.PRODUCT_MRP,CASE SIH.TRANTYPE WHEN 2 THEN -SIL.BOX ELSE SIL.BOX  END BOX,     
   CASE SIH.TRANTYPE WHEN 2 THEN -SIL.LTR ELSE SIL.LTR  END LTR,     
   CASE SIH.TRANTYPE WHEN 2 THEN -1 ELSE 1 END *      
 (CASE WHEN SIL.disccalculationbase=1 and SIL.DiscType=0 THEN      
 -- RETAILER PRICE OF ANY CUSTOMER      
 ((SIL.BASEPRICE)      
 -      
 (((CASE WHEN SIL.DiscType=0 THEN --GET PRICE AFTER MRP DISCOUNT      
  (coalesce(SIL.MRP,0)-(((coalesce(SIL.MRP,0)*coalesce((SIL.Disc),0))/100)))      
  WHEN SIL.DiscType=1 THEN (coalesce(SIL.MRP,0)- coalesce((SIL.Disc),0)) ELSE 0       
 END)/      
 (CASE WHEN SIL.ADDITIONALTAXBASIS=1 THEN --TAX CALCULATION      
 ISNULL(SIL.TAX1_PER,0)+ISNULL(SIL.TAX2_PER,0)      
 ELSE ISNULL(SIL.TAX1_PER,0)+ (ISNULL(SIL.TAX1_PER,0)*ISNULL(SIL.TAX2_PER,0)/100) END+100))*100))*SIL.BOX       
 ELSE SIL.CLAIM_DISC_AMT END)  AS [DISC_AMOUNT],      
   

   CASE SIH.TRANTYPE WHEN 2 THEN -SIL.SEC_DISC_AMOUNT ELSE SIL.SEC_DISC_AMOUNT  END SEC_DISC_AMOUNT,     
   SIL.DISC,ISNULL(CASE SIH.TRANTYPE WHEN 2 THEN -SIL.TDVALUE ELSE SIL.TDVALUE  END,0) AS TDVALUE    
  FROM [ax].[ACXSALEINVOICEHEADER] SIH    
  INNER JOIN [ax].[ACXSALEINVOICELINE] SIL ON SIL.INVOICE_NO = SIH.INVOICE_NO     
  AND SIL.SITEID= SIH.SITEID    
  INNER JOIN AX.INVENTTABLE INVT ON INVT.ITEMID = SIL.PRODUCT_CODE  AND INVT.BU_CODE LIKE CASE WHEN LEN(@BUCODE)>0 THEN @BUCODE ELSE '%' END
  INNER JOIN VW_CUSTOMERMASTER_HISTORY CUS ON CUS.CUSTOMER_CODE= SIH.CUSTOMER_CODE     
  AND CUS.SITE_CODE= SIH.SITEID --AND CUS.APPLICABLESCHEMEDISCOUNT in ('2','3')    
  INNER JOIN [AX].[ACXCUSTGROUPMASTER] GM ON CUS.CUST_GROUP=GM.CUSTGROUP_CODE    
  LEFT JOIN [ax].InventSite I on SIH.SiteId = I.SiteId    
  LEFT JOIN [ax].[LOGISTICSADDRESSSTATE] LS on LS.STATEID = I.STATECODE    
  WHERE SIH.INVOIC_DATE >=@FROMDATE and  SIH.INVOIC_DATE <=@TODATE   
  AND SIH.SITEID  IN (SELECT SITEID FROM #TMPSITELISTS) AND SIL.DISCTYPE IN (0,1)   
  AND CUS.Cust_Group<>'CG0006' AND ISNULL(SIL.SchemeCode,'')=''    
  AND SIH.TRANTYPE IN (1,2)  AND SIL.DISCTYPE IN (0,1)   
) AS RESULTOUTPUT    
GROUP BY STATECODE,SITEID,PRODUCT_GROUP    
    
IF OBJECT_ID('TEMPDB..#TMPDIST') IS NOT NULL BEGIN DROP TABLE #TMPDIST END    
SELECT DISTINCT STATECODE,SITEID,    
 (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG037')--'DISCOUNT IMP, TH & ALL-VARIABLE-SALE PRICE'     
 PRODUCT_GROUP,0 QTY,0 LTR,0 TDVALUE,0 DISC_AMOUNT,0 SEC_DISC_AMOUNT     
INTO #TMPDIST FROM #TMPTBL    
    
INSERT INTO #TMPDIST SELECT DISTINCT STATECODE,SITEID,    
 (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG036')--'DISCOUNT IMP, TH & ALL-VARIABLE-MRP'     
 PRODUCT_GROUP,0 QTY,0 LTR,0 TDVALUE,0 DISC_AMOUNT,0 SEC_DISC_AMOUNT FROM #TMPTBL    
    
INSERT INTO #TMPDIST SELECT DISTINCT STATECODE,SITEID,    
 (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG035')--'DISCOUNT IMP, TH & ALL-FIX'     
 PRODUCT_GROUP,0 QTY,0 LTR,0 TDVALUE,0 DISC_AMOUNT,0 SEC_DISC_AMOUNT FROM #TMPTBL    
    
INSERT INTO #TMPDIST SELECT DISTINCT STATECODE,SITEID,    
 (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG017')--'DISCOUNT BULK-FIX'     
 PRODUCT_GROUP,0 QTY,0 LTR,0 TDVALUE,0 DISC_AMOUNT,0 SEC_DISC_AMOUNT FROM #TMPTBL    
    
INSERT INTO #TMPDIST SELECT DISTINCT STATECODE,SITEID,    
 (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG018')--'DISCOUNT BULK-VARIABLE-MRP'     
 PRODUCT_GROUP,0 QTY,0 LTR,0 TDVALUE,0 DISC_AMOUNT,0 SEC_DISC_AMOUNT FROM #TMPTBL    
    
INSERT INTO #TMPDIST SELECT DISTINCT STATECODE,SITEID,    
 (SELECT NAME FROM AX.ACXTARGETSUBCATEGORY WHERE SUBCATEGORY='TG019')--'DISCOUNT BULK-VARIABLE-SALE PRICE'     
 PRODUCT_GROUP,0 QTY,0 LTR,0 TDVALUE,0 DISC_AMOUNT,0 SEC_DISC_AMOUNT FROM #TMPTBL    
    
SELECT STATECODE,SITEID,CATEGORY,SUBCATEGORY,QTY,LTR,DISC_AMOUNT,'' as [Description]    
 FROM     
 (SELECT Upper(#TMPDIST.STATECODE) as STATECODE,#TMPDIST.SITEID,    
  (SELECT NAME FROM AX.ACXTARGETCATEGORY WHERE CATEGORY='TG04') CATEGORY,    
  #TMPDIST.PRODUCT_GROUP SUBCATEGORY,SUM(ISNULL(#TMPTBL.QTY,0)) QTY,    
  SUM(ISNULL(#TMPTBL.LTR,0)) LTR,SUM(ISNULL(#TMPTBL.TDVALUE,0)) TDVALUE,    
  SUM(ISNULL(#TMPTBL.DISC_AMOUNT,0)) DISC_AMOUNT,    
  SUM(ISNULL(#TMPTBL.SEC_DISC_AMOUNT,0)) SEC_DISC_AMOUNT    
 FROM #TMPTBL    
  RIGHT OUTER JOIN #TMPDIST ON #TMPTBL.STATECODE=#TMPDIST.STATECODE     
  AND #TMPTBL.SITEID=#TMPDIST.SITEID AND #TMPTBL.PRODUCT_GROUP=#TMPDIST.PRODUCT_GROUP    
 GROUP BY #TMPDIST.STATECODE,#TMPDIST.SITEID,#TMPDIST.PRODUCT_GROUP    
 ) AA    
END
