USE [7200]
GO
/****** Object:  UserDefinedFunction [dbo].[UDF_GetSALESHIERARCHY]    Script Date: 9/16/2019 8:13:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER function [dbo].[UDF_GetSALESHIERARCHY](@USERCODE NVARCHAR(20))
RETURNS @TMPSalesHierarchy TABLE (HOSCODE NVARCHAR(50),HOSNAME NVARCHAR(150),
VPCODE NVARCHAR(50),VPNAME NVARCHAR(150),GMCODE NVARCHAR(50),GMNAME NVARCHAR(150),
DGMCODE NVARCHAR(50),DGMNAME NVARCHAR(150),RMCODE NVARCHAR(50),RMNAME NVARCHAR(150),
ZMCODE NVARCHAR(50),ZMNAME NVARCHAR(100),ASMCODE NVARCHAR(50),ASMNAME NVARCHAR(150),
EXECUTIVECODE NVARCHAR(50),EXECUTIVENAME NVARCHAR(50),DISTRIBUTOR NVARCHAR(50),
DISTRIBUTORNAME NVARCHAR(150),STATE  NVARCHAR(50),STATENAME  NVARCHAR(150),STATEWNAME  NVARCHAR(150),
SALEPOSITION NVARCHAR(20),CUSTGROUP NVARCHAR(10),CUSTGROUPDESC NVARCHAR(50),ACTIVATIONDATE DATE,
DEACTIVATIONDATE DATE)   
AS                
BEGIN
IF (SELECT COUNT(User_Code) FROM AX.ACXUSERMASTER WHERE User_Code=@USERCODE AND User_Type=0)>0
BEGIN
INSERT INTO @TMPSalesHierarchy
SELECT HOSCODE,HOSNAME,VPCODE,VPNAME,GMCODE,GMNAME,DGMCODE,DGMNAME,RMCODE,RMNAME,ZMCODE,ZMNAME,
ASMCODE,ASMNAME,EXECUTIVECODE,EXECUTIVENAME,SITEID DISTRIBUTOR,SITENAME [DISTRIBUTOR NAME],
STATE,[STATE NAME],STATE +' - '+[STATE NAME] as STATEWNAME,''  ROLECODE,
CHANNELGROUPCODE,CG.CUSTGROUP_NAME,SH.ACTIVATIONDATE,SH.DEACTIVATIONDATE    FROM vw_GETSALEHIERARCHY SH 
JOIN AX.ACXCUSTGROUPMASTER CG ON CG.CUSTGROUP_CODE=SH.CHANNELGROUPCODE
WHERE SH.SITEID=(SELECT TOP 1 Site_Code FROM AX.ACXUSERMASTER WHERE User_Code=@USERCODE)
END
ELSE  
BEGIN

Declare @HCMWORKERID nvarchar(10)
Set @HCMWORKERID=(SELECT TOP 1 HCMWORKERID FROM AX.Acx_PACUserCreation WHERE USERCODE=@USERCODE)

INSERT INTO @TMPSalesHierarchy
SELECT HOSCODE,HOSNAME,VPCODE,VPNAME,GMCODE,GMNAME,DGMCODE,DGMNAME,RMCODE,RMNAME,ZMCODE,ZMNAME,
ASMCODE,ASMNAME,EXECUTIVECODE,EXECUTIVENAME,SITEID DISTRIBUTOR,SITENAME [DISTRIBUTOR NAME],
STATE,[STATE NAME],STATE +' - '+[STATE NAME] as STATEWNAME,
(SELECT TOP 1 ROLECODE FROM AX.ACXEMPLOYEESUBPROFILELINE WHERE ((FROMDATE<GETDATE() AND TODATE>GETDATE()) OR (FROMDATE<GETDATE()
AND TODATE='1900-01-01')) AND BLOCKED=0 AND EMPLOYEE=@HCMWORKERID)  ROLECODE,
CHANNELGROUPCODE,CG.CUSTGROUP_NAME,SH.ACTIVATIONDATE,SH.DEACTIVATIONDATE       
FROM vw_GETSALEHIERARCHY SH
JOIN AX.ACXCUSTGROUPMASTER CG ON CG.CUSTGROUP_CODE=SH.CHANNELGROUPCODE
WHERE SH.EXECUTIVEEMP=@HCMWORKERID
OR SH.RMEMP=@HCMWORKERID
OR SH.ASMEMP=@HCMWORKERID
OR SH.ZMEMP=@HCMWORKERID
OR SH.DGMEMP=@HCMWORKERID
OR SH.GMEMP=@HCMWORKERID
OR SH.VPEMP=@HCMWORKERID
OR SH.HOSEMP=@HCMWORKERID
END    
RETURN                 
END 