USE [7200]
GO
/****** Object:  UserDefinedFunction [dbo].[UDF_GETCHANNELGROUPBYUSER]    Script Date: 8/31/2019 9:09:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER function [dbo].[UDF_GETCHANNELGROUPBYUSER](@USERCODE NVARCHAR(20))           

returns  @TMPCHANNELGROUP TABLE (CHANNELGROUPCODE NVARCHAR(50))    

AS          

BEGIN          

IF ((SELECT COUNT(User_Code) FROM AX.ACXUSERMASTER WHERE User_Code=@USERCODE AND User_Type=0)>0)  

BEGIN  

INSERT INTO @TMPCHANNELGROUP  SELECT CUSTGROUP_CODE FROM AX.ACXCUSTGROUPMASTER  

END  

ELSE  

BEGIN  

INSERT INTO @TMPCHANNELGROUP          

SELECT CG.CHANNELGROUPCODE FROM AX.ACXEMPLOYEESUBPROFILELINE PEFL JOIN AX.ACXPROFILEREGIONLINE PRL ON PRL.SUBROLECODE=PEFL.SUBPROFILECODE     

JOIN AX.ACXCHANNELGROUP CG  ON PRL.CHANNELPROFILECODE=CG.CHANNELPROFILECODE     

WHERE ((PEFL.FROMDATE<=GETDATE() AND PEFL.TODATE>=GETDATE()) OR (PEFL.FROMDATE<=GETDATE()         

AND PEFL.TODATE='1900-01-01')) AND PEFL.BLOCKED=0 AND PEFL.EMPLOYEE=(SELECT TOP 1 HCMWORKERID FROM AX.Acx_PACUserCreation WHERE USERCODE=@USERCODE)    

END  

RETURN           

END 